import {MISSIONS,DIFFICULTIES} from './content.js';
import {Game,DEFS,SIZE,terrain,PRODUCTION} from './engine.js';
import {Renderer,drawBuilding,drawUnitPortrait,loadArt} from './render.js';
import {Platform} from './platform.js';
import {t,desc,setLanguage,language} from './i18n.js';
const $=s=>document.querySelector(s);
const uiIcon=kind=>`<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">${{pause:'<path d="M8 5V19M16 5V19" stroke-width="3"/>',play:'<path d="M8 4L19 12 8 20Z" fill="currentColor" stroke="none"/>',arrow:'<path d="M6 18L18 6M7 6H18V17"/>',leaf:'<path d="M12 21V10M12 15C5 15 3 10 4 5 10 5 12 8 12 12M12 11C12 5 16 3 21 3 21 9 18 12 12 12"/>',castle:'<path d="M4 21V5H8V9H10V3H14V9H16V5H20V21ZM10 21V15H14V21"/>',home:'<path d="M3 11L12 3 21 11M5 10V21H19V10M10 21V14H14V21"/>',gear:'<path d="M10 3H14L15 6 18 7 21 7 22 11 19 13 19 16 19 18 15 21 12 19 9 19 7 21 3 18 4 14 3 11 2 9 6 6 9 6Z"/><circle cx="12" cy="12" r="3"/>',army:'<path d="M4 3L20 19M20 3L4 19M2 16L8 22M16 22L22 16M4 3L4 7 8 3M20 3V7L16 3"/>',people:'<circle cx="12" cy="6" r="3"/><path d="M6 21V16C6 9 18 9 18 16V21ZM3 20V15M21 20V15"/>',heart:'<path d="M12 21L3 12C-3 3 8 0 12 7 16 0 27 3 21 12Z"/>',flag:'<path d="M5 22V3M5 3C12 -1 16 7 22 3V14C16 18 12 10 5 14"/>'}[kind]||''}</svg>`;
const canvas=$('#game-canvas'),renderer=new Renderer(canvas),platform=new Platform();
$('.mission').append($('#caravan')||Object.assign(document.createElement('button'),{id:'caravan',className:'caravan parchment',hidden:true}));
$('.region [data-i18n="season"]').removeAttribute('data-i18n');
$('.region>div').insertAdjacentHTML('beforeend','<button id="weather-info" class="text-button"></button>');
$('.mission').insertAdjacentHTML('beforeend','<button id="mission-info" class="text-button"></button>');
$('.mission').prepend(Object.assign(document.createElement('div'),{id:'guide'}));
$('.map-tools').insertAdjacentHTML('beforebegin','<div class="minimap-panel parchment"><canvas id="minimap" width="132" height="132"></canvas><small data-i18n="map">Карта долины</small></div>');
$('.map-tools').insertAdjacentHTML('beforeend','<button class="icon-button" id="labels" title="Названия зданий" aria-label="Названия зданий">Аа</button>');
let game=new Game(),savedGame=null,started=false,paused=false,modalOpen=true,speed=1,tab='economy',selection=null,building=null,sdkPaused=false,adPaused=false,lastFrame=performance.now(),uiTimer=0,saveTimer=0,modalType='welcome',sound=true,audio=null;
try{sound=localStorage.getItem('amber-sound')!=='off';}catch{}
const iconPaths={wood:'<path d="M5 20L19 8 26 14 12 27Z" fill="#b09260"/><path d="M5 20L12 27 12 20 5 13Z" fill="#786b47"/><ellipse cx="8.5" cy="20" rx="5" ry="7" fill="#d0b278" transform="rotate(-40 8.5 20)"/><path d="M8 18L11 22M14 14L20 19" stroke="#806c47" fill="none"/>',stone:'<path d="M3 16L11 6 23 9 28 22 14 29 4 24Z" fill="#a1aa95"/><path d="M3 16L16 17 23 9 11 6Z" fill="#c8ccba"/><path d="M16 17L14 29 28 22 23 9Z" fill="#869681"/>',grain:'<path d="M16 29V5M16 12L9 6M16 18L9 12M16 24L9 18M16 12L23 6M16 18L23 12M16 24L23 18" stroke="#dab972" stroke-width="3"/>',flour:'<path d="M9 8L8 3H23L22 8Q29 16 26 28H6Q3 16 9 8Z" fill="#d0c7a5"/><path d="M10 8H22M16 14V23" stroke="#8c805d" stroke-width="2"/>',food:'<path d="M15 29L17 5M16 13L9 8M16 20L8 15M17 10L23 5M16 17L23 12M15 24L22 19" stroke="#d5b86d" stroke-width="2"/><path d="M9 8L6 3 11 5ZM8 15L5 10 11 12ZM23 5L26 1 20 3ZM23 12L26 8 20 10ZM22 19L25 15 19 17Z" fill="#ddc481"/>',gold:'<ellipse cx="16" cy="18" rx="11" ry="12" fill="#9e803f"/><ellipse cx="16" cy="15" rx="11" ry="12" fill="#d6b868"/><ellipse cx="16" cy="15" rx="7" ry="8" fill="none" stroke="#a68a44"/><path d="M16 10V20M13 12H18M13 18H18" stroke="#9e813c"/>'};
export function icon(kind){return `<svg viewBox="0 0 32 32" aria-hidden="true">${iconPaths[kind]||''}</svg>`;}
const costHTML=cost=>Object.entries(cost).map(([r,n])=>`<span class="cost-item">${icon(r)} ${n}</span>`).join('');
const fmt=n=>Math.floor(n).toLocaleString(language==='ru'?'ru-RU':'en-US');
let campaignProgress={unlocked:0,stars:{}},difficulty='normal';
let guideStamp='',pendingBuild=null,wallStart=null,wallLineMode=false,selectedUnits=[],orderMode=null;
$('.dock-top').insertAdjacentHTML('beforeend','<button class="icon-button" id="toggle-dock" aria-label="Свернуть постройки">⌄</button>');
$('#world').insertAdjacentHTML('beforeend','<div id="build-confirm" class="parchment" hidden></div>');
$('#toggle-dock').onclick=()=>{$('.build-dock').classList.toggle('collapsed');$('#toggle-dock').textContent=$('.build-dock').classList.contains('collapsed')?'⌃':'⌄';layoutTutorial();};
$('#resources').setAttribute('role','button');$('#resources').tabIndex=0;$('#resources').onclick=showEconomy;$('#resources').onkeydown=e=>{if(e.key==='Enter')showEconomy();};
function needsHTML(){const needs=game.needs();return `<div class="needs-grid">${Object.keys(needs).map(k=>`<div><strong>${needs[k]?'✓':'!'} ${t('need'+k)}</strong><small>${t('need'+k+(needs[k]?'Good':'Bad'))}</small></div>`).join('')}</div>`;}
function showEconomy(){modal(t('economyLedger'),`<p class="intro">${t('flowHint')}</p>${game.chain?`<div class="chain-note">${t('chainHint')}</div>${needsHTML()}<p class="modal-note">${t('storageCapacity')}: ${game.storageLimit} · ${t(game.night?'night':'day')} · ${t(game.weather)}</p><p class="modal-note">${t(game.weather+'Effect')} ${t('nightEffect')}</p>`:''}<div class="ledger"><div class="ledger-row ledger-head"><span>${t('resource')}</span><span>${t('stock')}</span><span>+ / ${t('second')}</span><span>− / ${t('second')}</span></div>${game.economyReport().map(r=>`<div class="ledger-row"><span>${icon(r.resource)} ${t(r.resource)}</span><strong>${fmt(r.stock)}</strong><span class="positive">${r.income.toFixed(1)}</span><span>${r.outgoing.toFixed(1)}</span></div>`).join('')}</div><p class="modal-note">${t('workAlerts')}</p>`,[{label:t('understood'),primary:true,action:closeModal}],'economy');}
function clearPreview(){pendingBuild=null;wallStart=null;renderer.preview=null;$('#build-confirm').hidden=true;$('#world').classList.remove('has-preview');}
function previewBuild(type,points){pendingBuild={type,points};renderer.preview=points;const plan=points.length>1?game.batchPlan(type,points):{error:game.buildReason(type,points[0].x,points[0].y),cost:DEFS[type].cost};renderer.previewValid=!plan.error;$('#world').classList.add('has-preview');const el=$('#build-confirm');el.hidden=false;el.style.bottom=(renderer.h-$('.build-dock').getBoundingClientRect().top+canvas.getBoundingClientRect().top+10)+'px';el.innerHTML=`<span>${t(type)}${points.length>1?' × '+points.length:''} · ${costHTML(plan.cost)}${plan.error?' · '+t(plan.error):''}</span><button class="primary" id="confirm-build" ${plan.error?'disabled':''}>${t('confirmBuild')}</button><button class="text-button" id="cancel-build">${t('cancel')}</button>`;$('#confirm-build').onclick=()=>{const p=pendingBuild;if(!p)return;const error=p.points.length>1?game.buildBatch(p.type,p.points):game.build(p.type,p.points[0].x,p.points[0].y);if(error){previewBuild(p.type,p.points);toast(t(error),true);return;}clearPreview();if(renderer.w<760){building=null;selection=game.at(p.points.at(-1).x,p.points.at(-1).y).id;renderer.build=null;renderer.selected=selection;updatePlacement();renderCards();}note('build');toast(t('built')+': '+t(p.type));save();updateUI();renderDetails();};$('#cancel-build').onclick=clearPreview;}
function guideType(){return({1:'farm',2:'archer',3:'tower'})[game.guideStep];}
function layoutTutorial(){
 const teaching=started&&game.guideStep<5;
 $('#world').classList.toggle('is-teaching',teaching);
 $('.mission').classList.toggle('guide-placing',teaching&&!!building);
 if(!teaching){renderer.anchor=null;return;}
 const canvasRect=canvas.getBoundingClientRect(),x=renderer.w*(renderer.w<760?.5:.59),screenX=canvasRect.left+x;
 let top=12,bottom=renderer.h-12;
 for(const selector of ['.scene-top .region','.scene-top .time-controls','.mission']){
  const el=$(selector);if(!el||!el.getClientRects().length)continue;const r=el.getBoundingClientRect();if(screenX>=r.left-20&&screenX<=r.right+20)top=Math.max(top,r.bottom-canvasRect.top+12);
 }
 for(const selector of ['.build-dock','.settlement-stats','.map-tools','#placement']){
  const el=$(selector);if(!el||!el.getClientRects().length)continue;const r=el.getBoundingClientRect();if(screenX>=r.left-30&&screenX<=r.right+30)bottom=Math.min(bottom,r.top-canvasRect.top-12);
 }
 const space=Math.max(0,bottom-top),clearance=88*renderer.scale+33;
 renderer.anchor={x,y:Math.min(bottom-24,top+Math.max(clearance,space*.7))};
}
function resizeView(){document.documentElement.style.setProperty('--game-height',`${window.visualViewport?.height||window.innerHeight}px`);renderer.resize();layoutTutorial();}
function showGuideAction(){
 const step=game.guideStep;
 if(step===0){game.guideStep=1;updateUI();save();return;}
 if(step===4){game.startWave(true);cancelSelection();renderer.focus(game.keep.x,game.keep.y);updateUI();save();return;}
 if(step===2){tab='army';renderTabs();renderCards();choose('archer');return;}
 tab=step===1?'economy':'defense';renderTabs();renderCards();if(building)cancelSelection();choose(step===1?'farm':'tower');
 const preferred=step===1?{x:9,y:15}:{x:6,y:12};let target=preferred;
 if(game.buildReason(building,target.x,target.y)){const options=[];for(let y=5;y<17;y++)for(let x=5;x<17;x++)if(!game.buildReason(building,x,y))options.push({x,y});target=options.sort((a,b)=>Math.hypot(a.x-preferred.x,a.y-preferred.y)-Math.hypot(b.x-preferred.x,b.y-preferred.y))[0];}
 if(target){renderer.target=target;renderer.focus(target.x,target.y);}
}
function updateGuide(){
 if(!started){$('#guide').hidden=true;return;}
 const before=game.guideStep;
 if(game.guideStep===1&&game.buildings.filter(b=>b.type==='farm').length>=2)game.guideStep=2;
 if(game.guideStep===2&&game.units.filter(u=>u.type==='archer').length>=4)game.guideStep=3;
 if(game.guideStep===3&&game.buildings.filter(b=>b.type==='tower').length>=3)game.guideStep=4;
 if(before!==game.guideStep){cancelSelection();renderer.target=null;renderer.focus(game.keep.x,game.keep.y);save();}
 const step=game.guideStep,stamp=[step,language,game.units.length].join(':');
 $('.mission').classList.toggle('teaching',step<5);$('#guide').hidden=step>=5;
 if(stamp===guideStamp){layoutTutorial();return;}guideStamp=stamp;
 if(step>=5){renderer.target=null;layoutTutorial();return;}
 $('#guide').innerHTML=`<div class="guide-eyebrow">${t('training')}</div><div class="guide-dots">${[0,1,2,3,4].map(n=>`<i class="${n<=step?'done':''}"></i>`).join('')}</div><h2>${t('guide'+step+'Title')}</h2><p class="guide-full-text">${t('guide'+step+'Text')}</p><p class="guide-short-text">${t('guide'+step+'Short')}</p><p class="guide-place-text">${t('guidePlace')}</p>${step===2?`<div class="recruit-progress">${Math.min(2,Math.max(0,game.units.filter(u=>u.type==='archer').length-2))} / 2</div>`:''}<button class="primary" id="guide-action">${t('guide'+step+'Action')}</button><button class="text-button" id="skip-guide">${t('skipGuide')}</button>`;
 $('#guide-action').onclick=showGuideAction;$('#skip-guide').onclick=()=>{game.guideStep=5;cancelSelection();renderer.target=null;renderer.focus(game.keep.x,game.keep.y);updateUI();save();};
 renderCards();
 layoutTutorial();
}
function active(){return started&&!paused&&!modalOpen&&!document.hidden&&!sdkPaused&&!adPaused&&!game.finished;}
function syncActive(){platform.gameplay(active());if(audio){if(active()&&sound)audio.resume().catch(()=>{});else audio.suspend().catch(()=>{});}$('#pause').innerHTML=uiIcon(paused?'play':'pause');$('#pause').setAttribute('aria-label',t('pause'));}
function audioInit(){if(!audio&&sound){try{audio=new (window.AudioContext||window.webkitAudioContext)();}catch{}}syncActive();}
function note(kind){if(!audio||!sound||!active())return;try{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(kind==='error'?160:kind==='wave'?190:kind==='win'?600:440,audio.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='wave'?100:kind==='error'?110:660,audio.currentTime+.16);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.26);}catch{}}
function toast(text,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=text;$('#toasts').append(el);setTimeout(()=>el.remove(),3500);if(error)note('error');}
function save(immediate=false){if(!started)return;platform.save(game,immediate);$('#save-state').textContent=t(platform.player?'savedCloud':'savedLocal');}
function localize(){document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));for(const[id,key]of[['settings','settings'],['help','help'],['zoom-in','zoomIn'],['zoom-out','zoomOut'],['reset-view','resetView'],['grid','grid'],['labels','labels']])$('#'+id).setAttribute('aria-label',t(key));$('#settings').innerHTML=uiIcon('gear');$('#call-wave').innerHTML=uiIcon('arrow');$('.wave-symbol').innerHTML=uiIcon('flag');document.querySelectorAll('.stat-icon').forEach((el,i)=>el.innerHTML=uiIcon(['people','heart','army'][i]));$('.brand').setAttribute('aria-label',t('title'));canvas.setAttribute('aria-label',t('valley')+'. '+t('buildPrompt'));$('#call-wave').title=t('callHint');$('#call-wave').setAttribute('aria-label',t('callHint'));renderResources();renderTabs();renderCards();renderDetails();updateUI();}
function renderResources(){$('#resources').innerHTML=['wood','stone','food','gold'].map(r=>`<div class="resource" title="${t(r)}">${icon(r)}<div><strong id="res-${r}">${fmt(game.resources[r])}</strong><small>${t(r)}</small></div></div>`).join('');}
const tabs={economy:['lumber','quarry','farm','mill','bakery','warehouse','market'],defense:['wall','gate','tower','barracks'],army:['archer','guard','army','rally'],village:['house','well','policy']};
function renderTabs(){$('#tabs').innerHTML=Object.keys(tabs).map(k=>`<button class="tab ${tab===k?'active':''}" data-tab="${k}">${uiIcon(({economy:'leaf',defense:'castle',army:'army',village:'home'})[k])}${t(k)}</button>`).join('');$('#tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;cancelSelection();renderTabs();renderCards();});}
function renderCards(){const container=$('#build-cards');container.innerHTML=tabs[tab].map((type,i)=>{const cost=DEFS[type]?.cost||(type==='archer'?{wood:15,gold:30,food:10}:type==='guard'?{stone:10,gold:40,food:10}:{});return `<button class="build-card ${building===type||selection===type?'active':''} ${started&&guideType()===type?'guide-highlight':''}" data-type="${type}" ${game.journey&&game.mode==='campaign'&&game.mapKey==='valley'&&['market','guard'].includes(type)?'disabled':''} title="${type==='policy'?t('policyHint'):desc(type)}"><canvas width="192" height="160" aria-hidden="true"></canvas><span class="name">${t(type)}</span><span class="card-purpose">${game.journey&&game.mode==='campaign'&&game.mapKey==='valley'&&['market','guard'].includes(type)?t('locked'):type==='farm'&&game.chain?t('cardGrainFarm'):t('card'+type[0].toUpperCase()+type.slice(1))}</span><span class="cost">${costHTML(cost)}</span><span class="key">${i+1}</span></button>`;}).join('');
 container.querySelectorAll('button').forEach(button=>{const type=button.dataset.type,ctx=button.querySelector('canvas').getContext('2d');ctx.scale(1.3,1.3);ctx.translate(74,92);if(DEFS[type])drawBuilding(ctx,{x:0,y:0,type,level:1});else if(['archer','guard'].includes(type))drawUnitPortrait(ctx,type);else{ctx.fillStyle='#8a9c76';ctx.font='36px Georgia';ctx.textAlign='center';ctx.fillText(type==='rally'?'⚑':'⚖',0,-17);}button.onclick=()=>choose(type);});const highlight=container.querySelector('.guide-highlight');if(highlight&&container.scrollWidth>container.clientWidth)container.scrollLeft=highlight.offsetLeft-(container.clientWidth-highlight.offsetWidth)/2;}
function choose(type){clearPreview();$('.build-dock').classList.remove('collapsed');$('#toggle-dock').textContent='⌄';audioInit();if(!started)return;if(['archer','guard'].includes(type)){const error=game.recruit(type);if(error)toast(t(error==='population'?'populationError':error==='barracks'?'barracksError':error),true);else{toast(t('recruited'));note('build');save();}renderDetails();updateUI();return;}
 if(type==='army'){selection='army';building=null;selectedUnits=game.units.map(u=>u.id);renderer.selectedUnits=new Set(selectedUnits);renderDetails();}else if(type==='policy'){building=null;selection='policy';renderer.selected=null;renderDetails();}else if(type==='rally'){building=null;selection='rally';orderMode='move';renderer.selected='rally';renderDetails();}else {building=building===type?null:type;selection=building;renderer.selected=null;renderDetails();}renderer.build=building;renderCards();updatePlacement();if((game.guideStep===1&&building==='farm')||(game.guideStep===3&&building==='tower')){const target=building==='farm'?{x:9,y:15}:{x:6,y:12};if(!game.buildReason(building,target.x,target.y)){renderer.target=target;renderer.focus(target.x,target.y);}}}
function cancelSelection(){selectedUnits=[];renderer.selectedUnits=new Set();orderMode=null;clearPreview();wallLineMode=false;selection=null;building=null;renderer.build=null;renderer.selected=null;renderer.hover=null;renderer.target=null;$('#details').hidden=true;$('#placement').hidden=true;renderCards();layoutTutorial();}
function updatePlacement(){const el=$('#placement');el.hidden=!building&&selection!=='rally';el.textContent=selection==='rally'?t('rallyPrompt'):t(building)+' · '+t('buildPrompt');if(building==='wall'){el.insertAdjacentHTML('beforeend',` <button id="wall-line" aria-pressed="${wallLineMode}">${t(wallLineMode?'wallLineOn':'wallLine')}</button>`);$('#wall-line').onclick=()=>{clearPreview();wallLineMode=!wallLineMode;updatePlacement();};}canvas.style.cursor=building||selection==='rally'?'crosshair':'grab';layoutTutorial();}
function workStatus(b){
 return game.villagers.filter(w=>w.buildingId===b.id).map(w=>{const role=w.role==='porter'?'porter':({farm:'farmer',lumber:'woodcutter',quarry:'mason',mill:'miller',bakery:'baker'})[b.type],state=w.blocked?'workBlocked':w.waitingInput?'workInput':w.storageFull?'workFull':({toWork:'workToSite',working:'workWorking',toWorkshop:'workToWorkshop',pickup:'workPickup',toKeep:'workToKeep'})[w.stage];return `<div class="worker-line"><span class="worker-dot ${w.blocked?'blocked':w.cargo>0?'carrying':''}"></span><div><strong>${t(role)}</strong><small>${t(state)}${w.cargo>0?' · '+Math.round(w.cargo):''}</small></div></div>`;}).join('');
}
function renderDetails(){const el=$('#details');if(!selection||(game.guideStep<5&&typeof selection==='string')||(building&&renderer.w<760)){el.hidden=true;return;}el.hidden=false;const head=title=>`<div class="detail-header"><span class="eyebrow">${t('village')}</span><button id="detail-close" aria-label="${t('close')}">✕</button></div><h2>${title}</h2>`;
 if(selection==='army'){el.innerHTML=head(t('armyOrders'))+`<p>${t('selectedCount')}: ${selectedUnits.length}</p><div class="army-filters">${['all','archer','guard'].map(k=>`<button class="action-button" data-filter="${k}">${t(k==='all'?'selectAll':k)}</button>`).join('')}</div>${['hold','defend','move','garrison'].map(k=>`<button class="action-button" data-order="${k}">${t('order'+k)}</button>`).join('')}<button id="repair-forts" class="action-button">${t('repairForts')}<small>${costHTML(game.repairPlan().cost)}</small></button><p>${t('garrisonHint')}</p>`;el.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{selectedUnits=game.units.filter(u=>b.dataset.filter==='all'||u.type===b.dataset.filter).map(u=>u.id);renderer.selectedUnits=new Set(selectedUnits);renderDetails();});el.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{if(b.dataset.order==='hold'){game.command(selectedUnits,'hold');save();toast(t('orderhold'));return;}orderMode=b.dataset.order;el.hidden=true;$('#placement').hidden=false;$('#placement').textContent=t('orderTarget');});$('#repair-forts').onclick=()=>{if(game.repairFortifications()){save();toast(t('repaired'));renderDetails();}else toast(t('resources'),true);};}
 else if(selection==='policy'){el.innerHTML=head(t('policy'))+`<p>${t('policyHint')}</p>${game.chain?needsHTML():''}`+['tax','rations'].map(k=>`<div class="settings-row"><span>${t(k)}</span><select id="policy-${k}">${[.5,1,1.5].map((v,i)=>`<option value="${v}" ${game[k]===v?'selected':''}>${t(['low','normal','high'][i])}</option>`).join('')}</select></div>`).join('');for(const k of['tax','rations'])$('#policy-'+k).onchange=e=>{game[k]=Number(e.target.value);save();};}
 else if(typeof selection==='string'){el.innerHTML=head(t(selection))+`<p>${selection==='farm'&&game.chain?t('grainFarmDesc'):desc(selection)}</p>`+(building?`<div class="detail-line"><span>${t('workers')}</span><strong>${DEFS[building].workers}</strong></div><div class="cost">${costHTML(DEFS[building].cost)}</div>`:'');}
 else {const b=game.buildings.find(b=>b.id===selection);if(!b){cancelSelection();return;}el.innerHTML=head(t(b.type))+`<p>${b.type==='farm'&&game.chain?t('grainFarmDesc'):desc(b.type)}</p><div class="detail-line"><span>${t('level')}</span><strong>${b.level} / 3</strong></div><div class="detail-line"><span>${t('health')}</span><strong id="detail-hp">${Math.ceil(b.hp)} / ${b.maxHp}</strong></div><div class="detail-line"><span>${t('workers')}</span><strong>${DEFS[b.type].workers}</strong></div>`;
  if(b.type==='warehouse')el.innerHTML+=`<p>${t('storageCapacity')}: ${game.storageLimit}</p>`;
  if(PRODUCTION[b.type])el.innerHTML+=`<div class="detail-line"><span>${t('workshopStock')}</span><strong id="stock-value">${fmt(b.stock||0)} ${icon(game.productionFor(b).resource)}</strong></div>${game.productionFor(b).input?`<div class="chain-note">${game.productionFor(b).amount*b.level} ${t(game.productionFor(b).input)} → ${game.productionFor(b).output*b.level} ${t(game.productionFor(b).resource)}</div>`:''}<div id="work-status">${workStatus(b)}</div><p class="delivery-note">${t('deliveryHint')}</p>`;
  if(b.type==='gate')el.innerHTML+=`<div class="detail-line"><span>${t('gateState')}</span><strong id="gate-state">${t(b.open?'opened':'closed')}</strong></div><button class="action-button primary" id="toggle-gate">${t(b.open?'gateClose':'gateOpen')}</button>`;
  if(!['keep','bridge'].includes(b.type))el.innerHTML+=b.level<3?`<button class="action-button primary" id="upgrade">${t('upgrade')}<small>${costHTML(game.upgradeCost(b))}</small></button>`:`<button class="action-button" disabled>${t('maxLevel')}</button>`;
  const missing=b.maxHp-b.hp;el.innerHTML+=`<button class="action-button" id="repair" ${missing<=0?'disabled':''}>${t('repair')}<small>${costHTML({wood:Math.ceil(missing/20),gold:Math.ceil(missing/30)})}</small></button>`;
  if(b.type==='market')el.innerHTML+=`<p>${t('marketTrade')}</p>`+['wood','stone','food'].map(r=>`<div class="detail-line"><span>${t(r)}</span><button data-buy="${r}" class="text-button">+50 / 25${icon('gold')}</button><button data-sell="${r}" class="text-button">−50 / 15${icon('gold')}</button></div>`).join('');
  if(!['keep','bridge'].includes(b.type))el.innerHTML+=`<button class="text-button danger" id="demolish" ${game.waveActive?'disabled':''}>${t('demolish')}</button>`;
  if($('#toggle-gate'))$('#toggle-gate').onclick=()=>{if(game.toggleGate(b.id)){toast(t(b.open?'gateOpened':'gateClosed'));note('build');save();renderDetails();updateUI();}};
  const action=fn=>{if(fn()){note('build');save();renderDetails();updateUI();}else toast(t('resources'),true);};
  if($('#upgrade'))$('#upgrade').onclick=()=>action(()=>{if(game.upgrade(b.id)){toast(t('upgraded'));return true;}return false;});
  $('#repair').onclick=()=>action(()=>{if(game.repair(b.id)){toast(t('repaired'));return true;}return false;});
  if($('#demolish'))$('#demolish').onclick=()=>{if(game.demolish(b.id)){save();cancelSelection();updateUI();}};
  el.querySelectorAll('[data-buy]').forEach(button=>button.onclick=()=>action(()=>game.trade(button.dataset.buy,true)));el.querySelectorAll('[data-sell]').forEach(button=>button.onclick=()=>action(()=>game.trade(button.dataset.sell,false)));
 }
 $('#detail-close').onclick=cancelSelection;
}
function updateUI(){updateGuide();for(const r of['wood','stone','food','gold'])if($('#res-'+r))$('#res-'+r).textContent=fmt(game.resources[r]);$('#day').textContent=t(game.night?'night':'day')+' '+game.day;$('#weather-info').textContent=game.chain?t(game.weather):t('season');$('#weather-info').title=game.chain?t(game.weather+'Effect'):t('season');$('#wave-count').textContent=(game.waveActive?game.wave-1:game.wave)+' / '+(game.mode==='campaign'?game.waveGoal:'∞');$('#wave-progress').style.width=Math.min(100,(game.waveActive?game.wave-1:game.wave)/game.waveGoal*100)+'%';$('#wave-label').textContent=t(game.waveActive?'siege':'nextSiege');const plan=game.wavePlan();$('#wave-label').title=t(plan.pattern)+' · '+t(plan.direction)+' · '+plan.count+' '+t('enemies');if(!game.waveActive&&game.guideStep>=5)$('#wave-label').textContent=t(plan.pattern)+' · '+t(plan.direction);const seconds=Math.max(0,Math.ceil(game.nextWave));$('#wave-timer').textContent=started&&game.guideStep<5?t('trainingSafe'):game.waveActive?t('enemies')+': '+(game.enemies.length+game.spawnLeft):String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');$('#call-wave').disabled=game.waveActive||!started||!!game.finished||game.guideStep<5;$('#population').textContent=game.population+' / '+game.capacity;$('#population').parentElement.title=t('efficiency')+': '+Math.round(game.labor*100)+'%';$('#happiness').textContent=Math.round(game.happiness)+'%';$('#army-count').textContent=game.units.length;$('#happiness').style.color=game.happiness<40?'#a55841':'';
 $('#caravan').hidden=!platform.sdk?.adv?.showRewardedVideo||!started||game.guideStep<5;$('#caravan').disabled=adPaused||game.supplyWave===game.wave;$('#caravan').textContent=t(game.supplyWave===game.wave?'suppliesReceived':'caravan');$('#caravan').title=t('caravanHint');
 if(game.buildings.filter(b=>b.type==='farm').length>=2)game.tutorial=Math.max(1,game.tutorial);if(game.units.filter(u=>u.type==='archer').length>=4&&game.tutorial>=1)game.tutorial=Math.max(2,game.tutorial);if(game.buildings.filter(b=>b.type==='tower').length>=3&&game.tutorial>=2)game.tutorial=3;
 $('#advisor-text').textContent=t(game.resources.food<5?(game.chain?'chainHungry':'hungry'):game.labor<.75?'shortWorkers':'advice'+game.tutorial);$('.mission>p').textContent=game.mode==='endless'?t('endlessText'):game.mission?game.mission.description[language==='ru'?0:1]:t('objective');$('.mission>.eyebrow').textContent=game.journey?t('chapterShort')+' '+(MISSIONS.findIndex(m=>m.id===game.mapKey)+1):t('chapter');$('.region h1').textContent=game.mission?game.mission.title[language==='ru'?0:1]:t('valley');$('#mission-info').hidden=!game.journey||game.guideStep<5;$('#mission-info').textContent=t('missionGoals');
 if(typeof selection==='number'){const b=game.buildings.find(b=>b.id===selection);if(!b)cancelSelection();else if($('#detail-hp')){$('#detail-hp').textContent=Math.ceil(b.hp)+' / '+b.maxHp;if($('#stock-value'))$('#stock-value').innerHTML=fmt(b.stock||0)+' '+icon(game.productionFor(b).resource);if($('#work-status'))$('#work-status').innerHTML=workStatus(b);if($('#gate-state'))$('#gate-state').textContent=t(b.open?'opened':'closed');$('#repair').disabled=b.hp>=b.maxHp;if($('#demolish'))$('#demolish').disabled=game.waveActive;}}
}
function modal(title,body,buttons,type){modalOpen=true;modalType=type;$('#modal').dataset.kind=type;$('#modal').hidden=false;const crest=$('.brand svg').outerHTML.replace('<svg','<svg class="crest"');$('#modal-content').innerHTML=crest+`<div class="eyebrow">${t('subtitle')}</div><h2>${title}</h2>${body}`+buttons.map((b,i)=>`<button class="${b.primary?'primary':'secondary'}" id="modal-button-${i}">${b.label}</button>`).join('');buttons.forEach((b,i)=>$('#modal-button-'+i).onclick=b.action);syncActive();$('#modal-button-0')?.focus({preventScroll:true});}
function closeModal(){modalOpen=false;$('#modal').hidden=true;syncActive();canvas.focus({preventScroll:true});}
function start(mode,restore=false,options={}){game=restore?savedGame:new Game(mode,{journey:true,mapKey:'valley',difficulty,campaignProgress,...options});difficulty=game.difficulty;campaignProgress=game.campaignProgress;started=true;paused=false;speed=1;$('#speed').textContent='1×';saveTimer=0;guideStamp='';tab='economy';cancelSelection();renderer.reset();renderer.focus(game.keep.x,game.keep.y);renderTabs();audioInit();closeModal();renderResources();renderDetails();updateUI();save();}
function welcome(){const buttons=[];if(savedGame&&!savedGame.finished)buttons.push({label:t('continue'),primary:true,action:()=>start(savedGame.mode,true)});buttons.push({label:t('campaign'),primary:!buttons.length,action:()=>start('campaign')},{label:t('endless'),action:()=>start('endless')},{label:t('chooseMission'),action:missionMenu});modal(t('gameName'),`<p class="intro">${t('welcomeText')}</p><div class="feature-list"><span><b>${uiIcon('leaf')}</b>${t('economyFeature')}</span><span><b>${uiIcon('castle')}</b>${t('buildFeature')}</span><span><b>${uiIcon('army')}</b>${t('siegeFeature')}</span></div>`,buttons,'welcome');$('#modal-content').insertAdjacentHTML('beforeend',`<div class="settings-row"><label for="difficulty">${t('difficulty')}</label><select id="difficulty">${Object.keys(DIFFICULTIES).map(k=>`<option value="${k}" ${k===difficulty?'selected':''}>${t(k)}</option>`).join('')}</select></div><p class="modal-note">${t('autosave')}</p>`);$('#difficulty').onchange=e=>difficulty=e.target.value;}
function weatherInfo(){modal(t('weather'),`<p class="intro">${t(game.weather+'Effect')}</p><p>${t('nightEffect')}</p>`,[{label:t('continue'),primary:true,action:closeModal}],'weather');}
$('#weather-info').onclick=weatherInfo;
function story(){const kind=game.pendingChoice.kind;modal(t('event'+kind),`<p class="intro">${t('event'+kind+'Text')}</p>`,game.choiceOptions().map((o,i)=>({label:t(o.key)+(Object.keys(o.cost).length?' · '+Object.entries(o.cost).map(([r,n])=>n+' '+t(r)).join(', '):''),primary:i===0,action:()=>{if(game.resolveChoice(i)){save(true);closeModal();updateUI();}else toast(t('resources'),true);}})),'story');game.choiceOptions().forEach((o,i)=>$('#modal-button-'+i).disabled=!game.canPay(o.cost));save(true);}
function pauseMenu(){if(!started)return;paused=true;save(true);modal(t('pause'),`<p class="intro">${t('pausedText')}</p>`,[{label:t('continue'),primary:true,action:()=>{paused=false;closeModal();}},{label:t('settings'),action:settings},{label:t('newGame'),action:newGame}],'pause');}
function settings(){modal(t('settings'),`<div class="settings-row"><label for="sound-enabled">${t('sound')}</label><input id="sound-enabled" type="checkbox" ${sound?'checked':''}></div><div class="settings-row"><label for="language">${t('language')}</label><select id="language"><option value="ru" ${language==='ru'?'selected':''}>Русский</option><option value="en" ${language==='en'?'selected':''}>English</option></select></div><div class="settings-row"><span>${t('fullscreen')}</span><button class="text-button" id="fullscreen">${t(document.fullscreenElement?'exitFullscreen':'enterFullscreen')}</button></div>`,[{label:t(started?'continue':'understood'),primary:true,action:()=>{if(started){paused=false;closeModal();}else welcome();}},...(started?[{label:t('save'),action:()=>{save(true);toast(t('saved'));}},{label:t('newGame'),action:newGame}]:[])],'settings');$('#sound-enabled').onchange=e=>{sound=e.target.checked;try{localStorage.setItem('amber-sound',sound?'on':'off');}catch{}audioInit();};$('#language').onchange=e=>{setLanguage(e.target.value);try{localStorage.setItem('amber-language',language);}catch{}localize();settings();};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{}settings();};}
function newGame(){modal(t('replace'),`<p class="intro">${t('replaceText')}</p>`,[{label:t('campaign'),primary:true,action:()=>start('campaign')},{label:t('endless'),action:()=>start('endless')},{label:t('cancel'),action:settings}],'new');}
function help(){modal(t('help'),`<ol class="help-list">${[1,2,3,4,5].map(i=>`<li>${t('help'+i)}</li>`).join('')}</ol>`,[{label:t('understood'),primary:true,action:()=>{if(started)closeModal();else welcome();}}],'help');}
function missionMenu(){modal(t('chooseMission'),`<div class="mission-list">${MISSIONS.map((m,i)=>`<button class="mission-card" data-mission="${m.id}" ${i>campaignProgress.unlocked?'disabled':''}><strong>${i+1}. ${m.title[language==='ru'?0:1]}</strong><span>${m.description[language==='ru'?0:1]}</span><small>${i>campaignProgress.unlocked?t('missionLocked'):'★'.repeat(campaignProgress.stars[m.id]||0)||t('notCompleted')}</small></button>`).join('')}</div>`,[{label:t('cancel'),action:welcome}],'missions');document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>start('campaign',false,{mapKey:b.dataset.mission}));}
function missionInfo(){const st=game.missionStatus(),keys=game.mapKey==='valley'?['population']:game.mapKey==='bridge'?['bridge']:['houses','convoy','mine'];modal(game.mission.title[language==='ru'?0:1],`<p class="intro">${game.mission.description[language==='ru'?0:1]}</p><div class="goal-list">${keys.map(k=>`<p>${st[k]?'✓':'○'} ${t('goal'+k)}</p>`).join('')}</div><p>${t('unlockHint')}</p>`,[{label:t('continue'),primary:true,action:closeModal}],'objectives');}
$('#mission-info').onclick=missionInfo;
function end(){campaignProgress=game.campaignProgress;save(true);const won=['victory','mission'].includes(game.finished),index=MISSIONS.findIndex(m=>m.id===game.mapKey);modal(t(won?'victory':'defeat'),`<p class="intro">${t(won?'victoryText':game.failReason==='bridge'?'bridgeLost':game.failReason==='houses'?'housesLost':'defeatText')}</p>${won&&game.journey?`<div class="mission-stars">${'★'.repeat(game.missionStars)}${'☆'.repeat(3-game.missionStars)}</div>`:''}<div class="result-score">${fmt(game.score)}</div><p class="modal-note">${t('score')} · ${t('sieges')}: ${game.waveActive?game.wave-1:game.wave}</p>`,[...(won&&game.finished==='mission'?[{label:t('nextMission'),primary:true,action:()=>start('campaign',false,{mapKey:MISSIONS[index+1].id})}]:won?[{label:t('keepPlaying'),primary:true,action:()=>{game.mode='endless';game.finished=null;game.nextWave=100;paused=false;closeModal();save();updateUI();}}]:[]),{label:t('retry'),primary:!won,action:()=>start(game.mode,false,{mapKey:game.mapKey,journey:game.journey})},{label:t('chooseMission'),action:missionMenu}],'end');}
$('#army-count').parentElement.onclick=()=>choose('army');$('#army-count').parentElement.style.cursor='pointer';$('#settings').onclick=settings;$('#help').onclick=help;$('.brand').onclick=e=>{e.preventDefault();started?pauseMenu():welcome();};$('#pause').onclick=()=>{if(modalOpen)return;if(paused){paused=false;syncActive();}else pauseMenu();};$('#speed').onclick=()=>{speed=speed===1?2:speed===2?3:1;$('#speed').textContent=speed+'×';};$('#call-wave').onclick=()=>{if(started&&!modalOpen&&game.startWave(true)){save();updateUI();}};
$('#caravan').onclick=async()=>{if(adPaused||modalOpen||game.supplyWave===game.wave)return;adPaused=true;syncActive();updateUI();const rewarded=await platform.rewarded();if(rewarded){game.supplyWave=game.wave;for(const[r,n]of Object.entries({wood:50,stone:50,food:100,gold:50}))game.grant(r,n);toast(t('supplies'));save(true);}else toast(t('adUnavailable'));adPaused=false;syncActive();updateUI();};
$('#zoom-in').onclick=()=>renderer.zoom=Math.min(2.3,renderer.zoom*1.18);$('#zoom-out').onclick=()=>renderer.zoom=Math.max(.55,renderer.zoom/1.18);$('#reset-view').onclick=()=>{renderer.reset();if(game.keep)renderer.focus(game.keep.x,game.keep.y);};$('#labels').onclick=()=>{renderer.labels=!renderer.labels;$('#labels').classList.toggle('enabled',renderer.labels);};$('#minimap').onclick=e=>{const rect=e.target.getBoundingClientRect();renderer.focus(Math.min(game.size-1,Math.floor((e.clientX-rect.left)/rect.width*game.size)),Math.min(game.size-1,Math.floor((e.clientY-rect.top)/rect.height*game.size)));};$('#grid').onclick=()=>{renderer.grid=!renderer.grid;$('#grid').style.background=renderer.grid?'#ddd7b7':'';};
window.addEventListener('resize',resizeView);window.visualViewport?.addEventListener('resize',resizeView);document.addEventListener('visibilitychange',()=>{if(document.hidden){save(true);if(started&&!modalOpen)pauseMenu();}syncActive();lastFrame=performance.now();});window.addEventListener('blur',()=>{if(started&&!modalOpen&&!adPaused){save(true);pauseMenu();}});window.addEventListener('pagehide',()=>save(true));window.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('keydown',e=>{if(['SELECT','INPUT'].includes(document.activeElement?.tagName)&&e.code!=='Escape')return;if(e.code==='Space'){e.preventDefault();if(!modalOpen&&started)pauseMenu();else if(modalType==='pause'){paused=false;closeModal();}}if(e.code==='Escape'){if(!modalOpen){if(selection)cancelSelection();else pauseMenu();}else if(started&&!['end','new'].includes(modalType)){paused=false;closeModal();}}if(!modalOpen&&/^[1-4]$/.test(e.key)){const type=tabs[tab][Number(e.key)-1];if(type)choose(type);}});
const pointers=new Map();let gesture=null,pinchDistance=0;
const pointerXY=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};};
canvas.addEventListener('pointerdown',e=>{if(modalOpen||!started)return;audioInit();canvas.setPointerCapture(e.pointerId);const p=pointerXY(e);pointers.set(e.pointerId,p);gesture={start:p,last:p,moved:false};if(pointers.size===2){const ps=[...pointers.values()];pinchDistance=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);gesture.moved=true;}});
canvas.addEventListener('pointermove',e=>{const p=pointerXY(e);renderer.hover=renderer.tile(p.x,p.y);if(!pointers.has(e.pointerId)||!gesture)return;pointers.set(e.pointerId,p);if(pointers.size===2){const ps=[...pointers.values()],d=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);if(pinchDistance>0)renderer.zoom=Math.max(.55,Math.min(2.3,renderer.zoom*d/pinchDistance));pinchDistance=d;gesture.moved=true;}else{if(Math.hypot(p.x-gesture.start.x,p.y-gesture.start.y)>5)gesture.moved=true;if(gesture.moved){renderer.pan.x+=p.x-gesture.last.x;renderer.pan.y+=p.y-gesture.last.y;renderer.pan.x=Math.max(-renderer.w,Math.min(renderer.w,renderer.pan.x));renderer.pan.y=Math.max(-renderer.h,Math.min(renderer.h,renderer.pan.y));}gesture.last=p;}});
canvas.addEventListener('pointerup',e=>{if(!pointers.has(e.pointerId))return;const click=pointers.size===1&&gesture&&!gesture.moved;pointers.delete(e.pointerId);if(pointers.size===0){gesture=null;pinchDistance=0;}else if(gesture){gesture.moved=true;gesture.last=[...pointers.values()][0];}if(!click||modalOpen)return;const p=pointerXY(e),tile=renderer.tile(p.x,p.y);if(building){if(building==='wall'&&wallLineMode){if(!wallStart){wallStart=tile;renderer.preview=[tile];toast(t('wallEnd'));}else{previewBuild('wall',game.wallLine(wallStart,tile));wallStart=null;}return;}if(renderer.w<760&&game.guideStep>=5){previewBuild(building,[tile]);renderer.focus(tile.x,tile.y);return;}const error=game.build(building,tile.x,tile.y);if(error)toast(t(error),true);else{note('build');save();toast(t('built')+': '+t(building));}updateUI();renderDetails();}else if(orderMode||selection==='rally'){const mode=orderMode||'move';const fort=mode==='garrison'?renderer.hitBuilding(game,p)||game.at(tile.x,tile.y):null;const target=fort?{x:fort.x,y:fort.y}:tile;if(game.command(selectedUnits.length?selectedUnits:game.units.map(u=>u.id),mode,target)){toast(t('rallySet'));cancelSelection();save();}else toast(t('terrain'),true);}else{const label=renderer.hitBuilding(game,p,true),unit=label?null:renderer.hitUnit(game,p);if(unit){selectedUnits=e.shiftKey?[...new Set([...selectedUnits,unit.id])]:[unit.id];renderer.selectedUnits=new Set(selectedUnits);selection='army';building=null;renderDetails();return;}const b=label||renderer.hitBuilding(game,p)||game.at(tile.x,tile.y);if(b){building=null;selection=b.id;renderer.selected=b.id;renderer.build=null;renderDetails();updatePlacement();}else cancelSelection();}});
canvas.addEventListener('pointercancel',()=>{pointers.clear();gesture=null;pinchDistance=0;});canvas.addEventListener('pointerleave',()=>{if(!pointers.size)renderer.hover=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();renderer.zoom=Math.max(.55,Math.min(2.3,renderer.zoom*(e.deltaY<0?1.09:.92)));},{passive:false});
function frame(now){const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;if(active()){for(let i=0;i<speed;i++)game.tick(dt);saveTimer+=dt;if(saveTimer>15){saveTimer=0;save();}}
 while(game.events.length){const e=game.events.shift();if(e.type==='wave'){toast(t('waveStart')+' '+e.text);note('wave');}if(e.type==='victory'){toast(t('waveWon'));note('win');}if(e.type==='destroyed')toast(t('destroyed')+': '+t(e.text),true);if(e.type==='convoySaved')toast(t('convoySaved'));if(e.type==='convoyLost')toast(t('convoyLost'),true);if(e.type==='end')end();}
 if(started&&!modalOpen&&!adPaused&&!sdkPaused&&!game.finished&&game.pendingChoice)story();
 renderer.render(game,game.time+(started?0:now/1000));uiTimer+=dt;if(uiTimer>.2){uiTimer=0;updateUI();}requestAnimationFrame(frame);}
resizeView();await loadArt();localize();$('#modal-content').innerHTML=`<div class="eyebrow">${t('title')}</div><h2>${t('valley')}</h2><p class="intro">${t('welcome')}</p>`;requestAnimationFrame(frame);
await platform.init();let lang=platform.language;try{lang=localStorage.getItem('amber-language')||lang;}catch{}setLanguage(lang);const saved=await platform.load();savedGame=Game.restore(saved?.game);if(savedGame){campaignProgress=savedGame.campaignProgress;difficulty=savedGame.difficulty;if(!savedGame.finished)game=savedGame;}platform.onPause(value=>{sdkPaused=value;if(value&&started&&!modalOpen&&!adPaused)pauseMenu();syncActive();});localize();welcome();platform.ready();
if(new URLSearchParams(location.search).has('test'))window.__amber={get game(){return game;},renderer,platform,start,save,active,choose,setGame:g=>{game=g;updateUI();}};
