import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,applyCommand,createSimulation,terrainAt} from '../src/state.js';
import {nextEnemyTile,HEALTH} from '../src/combat.js';
import {serializeSave,restoreSave} from '../src/save.js';
const build=(s,type,x,y)=>applyCommand(s,{type:'buildBuilding',buildingType:type,x,y});
function run(s,seconds){const sim=createSimulation(s);for(let i=0;i<seconds*10;i++)sim.advance(.1,true);}
function defended(){const s=createState();for(const [type,x,y]of [['wall',11,12],['wall',12,11],['wall',12,13],['gate',13,12],['tower',14,11],['guard',14,12]])assert.equal(build(s,type,x,y).ok,true);return s;}
function encounter(s,x,y){s.siege={phase:'active',warningTicks:0,spawned:3,spawnTicks:0,killed:2};s.enemies=[{id:s.nextId++,type:'raider',x,y,hp:45,cooldown:0,moveTicks:0}];}
test('defense placement pays all resources, rejects atomically, reserves entry and units',()=>{const s=defended();assert.deepEqual(s.resources,{wood:110,stone:44,food:90,gold:70});const before=structuredClone(s);assert.equal(build(s,'house',14,12).reason,'occupied');assert.equal(build(s,'wall',20,12).reason,'spawn');assert.deepEqual(s,before);for(const [type,key]of [['wall','stone'],['gate','wood'],['tower','gold'],['guard','food']]){const a=createState();a.resources[key]=0;const copy=structuredClone(a);assert.equal(build(a,type,13,12).reason,'resources');assert.deepEqual(a,copy);}});
test('closed walls force detour and an enclosure must be breached; gate opening changes passage',()=>{const s=createState();build(s,'wall',13,12);const first=nextEnemyTile(s,{x:14,y:12},terrainAt);assert.notDeepEqual(first,{x:13,y:12});const ring=defended();encounter(ring,14,12);ring.units=[];ring.buildings=ring.buildings.filter(b=>b.type!=='tower');const gate=ring.buildings.find(b=>b.type==='gate');assert.deepEqual(nextEnemyTile(ring,ring.enemies[0],terrainAt),{x:13,y:12});run(ring,1);assert.ok(gate.hp<HEALTH.gate);assert.equal(ring.buildings[0].hp,150);applyCommand(ring,{type:'toggleGate',id:gate.id});run(ring,1);assert.ok(ring.enemies[0].x===13);assert.ok(ring.buildings[0].hp<150);});
test('warning is finite, pause freezes combat, undefended keep loses and restart resets all',()=>{const s=createState();assert.equal(applyCommand(s,{type:'startSiege'}).ok,true);assert.equal(applyCommand(s,{type:'startSiege'}).ok,false);run(s,19.9);assert.equal(s.siege.phase,'warning');assert.equal(s.enemies.length,0);const before=structuredClone(s);createSimulation(s).advance(20,false);assert.deepEqual(s,before);run(s,40);assert.equal(s.siege.phase,'defeat');assert.equal(s.buildings[0].hp,0);const done=structuredClone(s);run(s,10);assert.deepEqual(s,done);assert.equal(build(s,'wall',13,12).reason,'finished');applyCommand(s,{type:'restart'});assert.deepEqual(s,createState());});
test('tower and holding defender win a real finite siege; dead enemies disappear',()=>{const s=defended();applyCommand(s,{type:'startSiege'});run(s,60);assert.equal(s.siege.phase,'victory');assert.equal(s.siege.killed,3);assert.equal(s.enemies.length,0);assert.ok(s.buildings[0].hp>0);assert.deepEqual(s.units.map(u=>[u.x,u.y]),[[14,12]]);const copy=structuredClone(s);run(s,10);assert.deepEqual(s,copy);});
test('raiders kill defenders and destroy blocking structures without walking through them',()=>{const s=createState();build(s,'guard',13,12);s.units[0].hp=12;s.units[0].cooldown=10;encounter(s,14,12);run(s,.1);assert.equal(s.units.length,0);const ring=defended();ring.units=[];ring.buildings=ring.buildings.filter(b=>b.type!=='tower');const gate=ring.buildings.find(b=>b.type==='gate');gate.hp=12;encounter(ring,14,12);run(ring,.1);assert.ok(!ring.buildings.some(b=>b.id===gate.id));assert.equal(ring.enemies[0].x,14);run(ring,1);assert.equal(ring.enemies[0].x,13);});
test('active and finished combat save/load continues deterministically including timers',()=>{const a=defended();applyCommand(a,{type:'startSiege'});run(a,22.7);const b=restoreSave(serializeSave(a,false)).state;const sa=createSimulation(a),sb=createSimulation(b);for(let i=0;i<600;i++){const dt=[.017,.083,.21][i%3];sa.advance(dt,true);sb.advance(dt,true);}assert.deepEqual(a,b);assert.equal(a.siege.phase,'victory');assert.deepEqual(restoreSave(serializeSave(a,true)).state,a);const lose=createState();applyCommand(lose,{type:'startSiege'});run(lose,60);assert.deepEqual(restoreSave(serializeSave(lose,false)).state,lose);});
test('validated AK-003 saves evolve locally; invalid combat saves are rejected',()=>{const old=createState();old.schemaVersion=1;delete old.siege;delete old.units;delete old.enemies;for(const b of old.buildings)delete b.hp;const migrated=restoreSave(JSON.stringify({schemaVersion:1,state:old,paused:true}));assert.deepEqual(migrated.state,createState());assert.equal(migrated.paused,true);old.buildings[0].type='tower';assert.equal(restoreSave(JSON.stringify({schemaVersion:1,state:old,paused:true})),null);for(const mutate of [s=>s.siege.phase='unknown',s=>s.siege.spawned=4,s=>s.siege.warningTicks=1,s=>s.buildings[0].hp=Infinity,s=>s.buildings.find(b=>b.type==='gate').open=1,s=>s.units[0].cooldown=11,s=>s.units[0].id=1,s=>s.units[0].type='knight',s=>s.siege.killed=1]){const s=defended();mutate(s);assert.throws(()=>serializeSave(s,false));}});

test('old east-shore building is attacked from the new landing, never overlaps a spawn',()=>{const s=createState();assert.equal(build(s,'house',19,12).ok,true);applyCommand(s,{type:'startSiege'});run(s,20.1);assert.equal(s.enemies[0].x,20);assert.ok(s.buildings.find(b=>b.x===19&&b.y===12).hp<60);assert.ok(restoreSave(serializeSave(s,false)));run(s,40);assert.equal(s.siege.phase,'defeat');});
