import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createState,createSimulation,applyCommand} from '../src/state.js';
import {SAVE_KEY,serializeSave,restoreSave} from '../src/save.js';
import {createLocalPlatform} from '../src/platform.js';
function settlement(){const s=createState();applyCommand(s,{type:'buildBuilding',buildingType:'farm',x:13,y:12});applyCommand(s,{type:'buildBuilding',buildingType:'lumber',x:5,y:8});const sim=createSimulation(s);for(let i=0;i<301;i++)sim.advance(.1,true);sim.advance(.037,true);return s;}
test('exact settlement roundtrip excludes transient view state',()=>{const s=settlement();s.camera={x:5};s.selection=2;s.preview={x:1};const restored=restoreSave(serializeSave(s,true));delete s.camera;delete s.selection;delete s.preview;assert.deepEqual(restored,{schemaVersion:2,state:s,paused:true});assert.equal(restored.state.population,13);assert.notEqual(restored.state.resources.food,Math.round(restored.state.resources.food));});
test('deterministic continuation includes fractional fixed step and growth',()=>{const a=settlement(),b=restoreSave(serializeSave(a,false)).state,sa=createSimulation(a),sb=createSimulation(b);for(let i=0;i<1000;i++){const seconds=[.017,.089,.25,.043][i%4];sa.advance(seconds,true);sb.advance(seconds,true);}assert.deepEqual(a,b);sa.advance(10,false);sb.advance(10,false);assert.equal(a.simulationRemainder,0);assert.deepEqual(a,b);});
test('reject corrupt JSON, missing data and incompatible versions without mutation',()=>{for(const raw of ['', '{', 'null','[]','{}','{"schemaVersion":1e999}'])assert.equal(restoreSave(raw),null);for(const mutate of [v=>v.schemaVersion=999,v=>v.state.schemaVersion=999,v=>v.state.mapId='legacy',v=>delete v.state.tick,v=>v.paused='yes',v=>v.extra=1]){const v=JSON.parse(serializeSave(settlement(),false));mutate(v);assert.equal(restoreSave(JSON.stringify(v)),null);}});
test('reject nonfinite, negative and malformed numeric fields',()=>{for(const path of ['tick','nextId','population','growthSeconds','simulationRemainder','resources.wood','resources.food','resources.stone','resources.gold'])for(const value of [NaN,Infinity,-Infinity,-1,'12',null]){const s=settlement(),parts=path.split('.');(parts.length===2?s[parts[0]]:s)[parts.at(-1)]=value;assert.throws(()=>serializeSave(s,false));}const raw=serializeSave(settlement(),false).replace('"stone":100','"stone":1e999');assert.equal(restoreSave(raw),null);});
test('reject invalid IDs, building types, positions, capacity and timers',()=>{for(const mutate of [s=>s.buildings[1].id=1,s=>s.nextId=2,s=>s.buildings[1].type='toString',s=>s.buildings[1].type='castle',s=>s.buildings[1].x=24,s=>Object.assign(s.buildings[1],{x:1,y:11}),s=>Object.assign(s.buildings[1],{x:12,y:12}),s=>s.buildings[0].type='house',s=>s.buildings[0].x=11,s=>s.buildings.at(-1).x=13,s=>s.population=100,s=>s.growthSeconds=30,s=>s.simulationRemainder=.1,s=>s.tick=.5,s=>s.buildings[1].id=Number.MAX_SAFE_INTEGER+1]){const s=settlement();mutate(s);assert.throws(()=>serializeSave(s,false));}});
test('local adapter isolates legacy data and handles read/write/access failures',()=>{const values=new Map([['amber-keep-save-v8','legacy']]),reads=[],storage={getItem(k){reads.push(k);return values.get(k)??null;},setItem(k,v){values.set(k,v);}},p=createLocalPlatform(()=>storage),s=settlement();assert.equal(p.load().status,'empty');assert.equal(p.save(s,true).status,'saved');assert.deepEqual(p.load().state,s);assert.deepEqual(reads,[SAVE_KEY,SAVE_KEY]);assert.equal(values.get('amber-keep-save-v8'),'legacy');values.set(SAVE_KEY,'broken');assert.equal(p.load().status,'invalid');for(const provider of [()=>{throw Error('blocked');},()=>({getItem(){throw Error('blocked');},setItem(){throw Error('quota');}})]){const failed=createLocalPlatform(provider);assert.equal(failed.load().status,'unavailable');assert.equal(failed.save(s,false).status,'unavailable');}assert.deepEqual(s,settlement());});
