import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,terrainAt,applyCommand,buildReason,createSimulation} from '../src/state.js';

test('deterministic serializable state and all four terrain types',()=>{assert.deepEqual(createState(),createState());assert.deepEqual(JSON.parse(JSON.stringify(createState())),createState());assert.equal(terrainAt(0,0),'forest');assert.equal(terrainAt(16,14),'rock');assert.equal(terrainAt(22,12),'water');assert.equal(terrainAt(13,12),'grass');});
test('house creates one stable ID and charges exactly once',()=>{const state=createState();assert.equal(applyCommand(state,{type:'buildHouse',x:13,y:12}).ok,true);assert.equal(state.buildings.length,4);assert.deepEqual(state.resources,{wood:115,stone:100,food:100,gold:85});assert.equal(state.buildings.at(-1).id,4);const snapshot=structuredClone(state);assert.equal(applyCommand(state,{type:'buildHouse',x:13,y:12}).reason,'occupied');assert.deepEqual(state,snapshot);});
test('terrain, occupancy, bounds and insufficient stock reject atomically',()=>{for(const [x,y,reason]of [[0,0,'terrain'],[16,14,'terrain'],[22,12,'terrain'],[12,12,'occupied'],[-1,2,'outside'],[1.5,2,'outside']]){const state=createState(),before=structuredClone(state);assert.equal(applyCommand(state,{type:'buildHouse',x,y}).reason,reason);assert.deepEqual(state,before);}for(const resource of ['wood','gold']){const state=createState();state.resources[resource]=0;const before=structuredClone(state);assert.equal(buildReason(state,13,12),'resources');assert.equal(applyCommand(state,{type:'buildHouse',x:13,y:12}).ok,false);assert.deepEqual(state,before);}});
test('cancel never mutates state',()=>{const state=createState(),before=structuredClone(state);applyCommand(state,{type:'cancel'});assert.deepEqual(state,before);});
test('fixed-step determinism, pause discards inactive time, long frames bounded',()=>{const a=createState(),b=createState(),simA=createSimulation(a),simB=createSimulation(b);for(let i=0;i<100;i++)simA.advance(.01,true);for(let i=0;i<10;i++)simB.advance(.1,true);assert.equal(a.tick,10);assert.equal(a.tick,b.tick);simA.advance(30,false);assert.equal(a.tick,10);simA.advance(.1,true);assert.equal(a.tick,11);simA.advance(100,true);assert.ok(a.tick<=14);});
