import {test,expect} from '@playwright/test';
async function targetClick(page,touch=false){const p=await page.evaluate(()=>{const r=window.__amber.renderer,p=r.project(r.target.x,r.target.y),rect=document.querySelector('#game-canvas').getBoundingClientRect();return{x:p.x+rect.left,y:p.y+rect.top};});if(touch)await page.touchscreen.tap(p.x,p.y);else await page.mouse.click(p.x,p.y);}
for(const {mobile,viewport} of [{mobile:false,viewport:{width:1440,height:900}},{mobile:false,viewport:{width:1280,height:720}},{mobile:false,viewport:{width:1280,height:633}},{mobile:true,viewport:{width:390,height:844}}])test(`guided first session on ${mobile?'phone':'desktop'} ${viewport.width}x${viewport.height}`,async({browser})=>{
 const context=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/?test=1');await page.getByRole('button',{name:'Начать кампанию',exact:true}).click();await expect(page.getByRole('heading',{name:'Это ваш новый дом'})).toBeVisible();expect(await page.evaluate(()=>window.__amber.renderer.scale)).toBeGreaterThanOrEqual(.8);
 await page.evaluate(()=>{for(let i=0;i<600;i++)window.__amber.game.tick(.25);});expect(await page.evaluate(()=>window.__amber.game.wave)).toBe(0);expect(await page.evaluate(()=>window.__amber.game.nextWave)).toBe(110);
 await page.locator('#guide-action').click();await expect(page.getByRole('heading',{name:'1. Постройте ферму'})).toBeVisible();await page.locator('#guide-action').click();expect(await page.evaluate(()=>window.__amber.renderer.target)).toEqual({x:9,y:15});await targetClick(page,mobile);
 await expect(page.getByRole('heading',{name:'2. Наймите двух лучников'})).toBeVisible();await page.locator('#guide-action').click();await expect(page.locator('.recruit-progress')).toHaveText('1 / 2');await page.locator('#guide-action').click();await expect(page.getByRole('heading',{name:'3. Усильте оборону башней'})).toBeVisible();
 await page.locator('#guide-action').click();await targetClick(page,mobile);await expect(page.getByRole('heading',{name:'Поселение готово к обороне'})).toBeVisible();expect(await page.evaluate(()=>window.__amber.game.wave)).toBe(0);await page.locator('#guide-action').click();expect(await page.evaluate(()=>window.__amber.game.wave)).toBe(1);expect(await page.evaluate(()=>window.__amber.game.guideStep)).toBe(5);expect(errors).toEqual([]);await context.close();
});
test('tutorial progress survives reload and building label selects the correct building',async({page})=>{
 await page.goto('/?test=1');await page.getByRole('button',{name:'Начать кампанию',exact:true}).click();await page.locator('#guide-action').click();await page.reload();await page.getByRole('button',{name:'Продолжить',exact:true}).click();await expect(page.getByRole('heading',{name:'1. Постройте ферму'})).toBeVisible();await page.locator('#skip-guide').click();
 const p=await page.evaluate(()=>{const r=window.__amber.renderer,b=window.__amber.game.keep,p=r.project(b.x,b.y),rect=document.querySelector('#game-canvas').getBoundingClientRect();return{x:p.x+rect.left,y:p.y+23*r.scale+12+rect.top};});await page.mouse.click(p.x,p.y);await expect(page.locator('#details h2')).toHaveText('Цитадель');
});
