import test from 'node:test';import assert from 'node:assert/strict';import {Game} from '../src/engine.js';
const tick=(g,n)=>{for(let i=0;i<n*10;i++)g.tick(.1);};
test('grain is processed into flour and baked food is delivered rather than granted immediately',()=>{const g=new Game('campaign',{journey:true});g.resources.grain=0;g.resources.flour=0;g.resources.food=50;const mill=g.buildings.find(b=>b.type==='mill'),bakery=g.buildings.find(b=>b.type==='bakery');g.villagers=g.villagers.filter(w=>[mill.id,bakery.id].includes(w.buildingId));tick(g,10);assert.equal(mill.stock,0);assert.equal(bakery.stock,0);assert.ok(g.villagers.some(w=>w.waitingInput));g.resources.grain=30;tick(g,30);assert.ok(g.flowLog.some(f=>f.resource==='grain'&&f.amount<0));assert.ok(g.flowLog.some(f=>f.resource==='flour'&&f.amount>0));assert.ok(g.flowLog.some(f=>f.resource==='food'&&f.amount>0));assert.ok(g.flowLog.filter(f=>f.resource==='food'&&f.amount>0).reduce((n,f)=>n+f.amount,0)>=8);});
test('nearby warehouse receives cargo and blocked warehouses fall back to a reachable depot',()=>{const g=new Game('campaign',{journey:true});assert.equal(g.build('warehouse',5,13),null);const b=g.buildings.find(b=>b.type==='lumber'),w=g.villagers.find(w=>w.buildingId===b.id&&w.role==='porter'),warehouse=g.at(5,13);w.x=b.x;w.y=b.y;assert.equal(g.depotFor(w).id,warehouse.id);assert.equal(g.storageLimit,1800);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])g.add('wall',warehouse.x+dx,warehouse.y+dy);assert.equal(g.depotFor(w).id,g.keep.id);});
test('events charge once, reject unaffordable choices and survive restoring',()=>{const g=new Game('campaign',{journey:true});g.pendingChoice={id:1,kind:'merchant'};g.resources.gold=0;const stock=g.resources.stone;assert.equal(g.resolveChoice(0),false);assert.equal(g.resources.stone,stock);const restored=Game.restore(g.snapshot());assert.equal(restored.pendingChoice.kind,'merchant');restored.resources.gold=40;assert.equal(restored.resolveChoice(0),true);assert.equal(restored.resources.gold,0);assert.equal(restored.resources.stone,stock+80);assert.equal(restored.resolveChoice(0),false);});
test('weather, night and threats have real production or happiness consequences',()=>{const g=new Game('campaign',{journey:true});g.time=120;assert.equal(g.weather,'rain');assert.equal(g.night,true);g.time=240;assert.equal(g.weather,'drought');assert.equal(g.night,false);const h=g.buildings.find(b=>b.type==='house');g.enemies=[{x:h.x,y:h.y,hp:100}];assert.equal(g.needs().safety,false);g.happiness=75;g.produce();assert.ok(g.happiness<75);});
test('legacy saves retain direct farm food production',()=>{const g=new Game(),save=g.snapshot();delete save.chain;delete save.mapKey;const restored=Game.restore(save);assert.equal(restored.chain,false);assert.equal(restored.productionFor(restored.buildings.find(b=>b.type==='farm')).resource,'food');assert.equal(restored.resources.grain,undefined);});
test('rain and drought change actual grain harvest, and night reduces actual archer reach',()=>{const harvest=time=>{const g=new Game('campaign',{journey:true});g.time=time;const farm=g.buildings.find(b=>b.type==='farm'),w=g.villagers.find(w=>w.buildingId===farm.id&&w.role==='harvester');w.site=g.worksite(farm);w.stage='working';w.progress=3;g.tick(.1);return w.cargo;};assert.ok(harvest(120)>harvest(0));assert.ok(harvest(240)<harvest(0));const shot=time=>{const g=new Game('campaign',{journey:true});g.time=time;const u=g.units.find(u=>u.type==='archer');u.x=12;u.y=19;u.cooldown=0;g.enemies=[{id:999,type:'raider',x:16,y:19,hp:1000,maxHp:1000,cooldown:1,speed:0,damage:0,path:[],repath:1}];g.tick(.1);return g.enemies[0].hp;};assert.ok(shot(0)<shot(120));});
test('full storage keeps porter cargo until space exists, without counting duplicate income',()=>{const g=new Game('campaign',{journey:true}),b=g.buildings.find(b=>b.type==='lumber'),w=g.villagers.find(w=>w.buildingId===b.id&&w.role==='porter');g.resources.wood=g.storageLimit;w.stage='toKeep';w.cargo=10;w.resource='wood';w.x=g.keep.x+.35;w.y=g.keep.y+.45;g.tick(.1);assert.equal(w.cargo,10);assert.equal(w.storageFull,true);g.resources.wood-=10;g.tick(.1);assert.equal(w.cargo,0);assert.equal(g.resources.wood,g.storageLimit);assert.equal(g.flowLog.filter(f=>f.resource==='wood'&&f.amount>0).reduce((n,f)=>n+f.amount,0),10);});
