import {chromium} from 'playwright';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
for(const phone of [false,true]){const context=await browser.newContext(phone?{viewport:{width:393,height:700},isMobile:true,hasTouch:true}:{viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:3000/?test=1');await page.getByRole('button',{name:'Начать кампанию',exact:true}).click();await page.locator('#skip-guide').click();await page.evaluate(()=>{const g=__amber.game;g.guideStep=5;g.nextWave=999;__amber.renderer.labels=false;});await page.locator('#toggle-dock').click();await page.screenshot({path:`publishing/v8-${phone?'mobile':'settlement'}.png`});if(phone){await page.locator('#resources').click();await page.screenshot({path:'publishing/v8-mobile-economy.png'});}else{
const timing=await page.evaluate(async()=>{const deltas=[];let last=performance.now();await new Promise(resolve=>{const until=last+2000;function f(now){deltas.push(now-last);last=now;if(now<until)requestAnimationFrame(f);else resolve();}requestAnimationFrame(f);});return {mean:deltas.reduce((a,b)=>a+b)/deltas.length,frames:deltas.length,max:Math.max(...deltas)};});console.log('Desktop frame intervals (ms):',timing);
await page.evaluate(async()=>{const {Game}=await import('/src/engine.js');__amber.setGame(new Game('campaign',{journey:true,mapKey:'bridge'}));__amber.game.guideStep=5;__amber.renderer.focus(18,11);});await page.screenshot({path:'publishing/v8-bridge.png'});
await page.evaluate(()=>{const g=__amber.game;g.time=125;g.wave=1;g.startWave();g.nextChoice=999;for(let i=0;i<80;i++)g.tick(.1);__amber.renderer.focus(19,11);});await page.screenshot({path:'publishing/v8-rain.png'});
await page.evaluate(async()=>{const {Game}=await import('/src/engine.js');__amber.setGame(new Game('campaign',{journey:true,mapKey:'village'}));const g=__amber.game;g.guideStep=5;g.wave=2;g.nextWave=999;g.tick(.1);__amber.renderer.focus(11,23);});await page.screenshot({path:'publishing/v8-convoy.png'});
}console.log(phone?'Phone':'Desktop',errors);await context.close();}
await browser.close();
